name: CI Testing
# This workflow is triggered on pushes and PRs to the repository.

on:
  push:
    branches:
      - dev
  pull_request:
    paths-ignore:
      # ignore github workflows except for the current one
      - ".github/**"
      - "!.github/workflows/pytest.yml"
  release:
    types: [published]

# Cancel if a newer run with the same workflow name is queued
concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
  pytest:
    name: Run pytest python - ${{ matrix.PYTHON_VERSION }}
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        PYTHON_VERSION: ["3.11"]
    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip -r requirements-dev.txt
          pip install -e .

      - name: Test with pytest
        run: |
          python3 -m pytest --color=yes --cov --durations=0 && exit_code=0|| exit_code=$?
          # don't fail if no tests were collected, e.g. for test_licence.py
          if [ "${exit_code}" -eq 5 ]; then
            echo "No tests were collected"
            exit 0
          elif [ "${exit_code}" -ne 0 ]; then
            echo "Tests failed with exit code ${exit_code}"
            exit 1
          fi

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage_${{ matrix.test }}
          path: .coverage
